"use client";
import { ParallaxScroll } from "@/components/ui/parallax-scroll";

export default function Gallery() {
  return <ParallaxScroll images={images} />;
}

const images = [
  "/gallery/01.JPG",
  "/gallery/02.JPG",
  "/gallery/03.JPG",
  "/gallery/04.JPG",
  "/gallery/05.jpg",
  "/gallery/06.JPG",
  "/gallery/07.JPG",
  "/gallery/08.JPG",
  "/gallery/09.JPG",
  "/gallery/10.JPG",
  "/gallery/11.JPG",
  "/gallery/12.JPG",
  "/gallery/13.JPG",
  "/gallery/14.JPG",
  "/gallery/15.JPG",
  "/gallery/16.jpg",
  "/gallery/17.jpg",
  "/gallery/18.jpg",
  "/gallery/19.jpg",
  "/gallery/20.jpg",
  "/gallery/21.png",
  "/gallery/22.jpg",
  "/gallery/23.jpg",
  "/gallery/24.jpg",
  "/gallery/25.jpg",
  "/gallery/26.jpg",
  "/gallery/27.jpg",
  "/gallery/28.jpg",
  "/gallery/29.jpg",
  "/gallery/30.jpg",
  "/gallery/31.jpg",
  "/gallery/32.jpg",
  "/gallery/33.jpg",
  "/gallery/34.jpg",
  "/gallery/35.jpg",
  "/gallery/36.jpg",
  "/gallery/37.jpg",
  "/gallery/38.jpg",
  "/gallery/39.jpg",
  "/gallery/40.jpg",
  "/gallery/41.jpg",
  "/gallery/42.jpg",
  "/gallery/43.jpg",
  "/gallery/44.jpg",
  "/gallery/45.jpg",
  "/gallery/46.jpg",
  "/gallery/47.jpg",
  "/gallery/48.jpg",
  "/gallery/49.jpg",
  "/gallery/50.jpg",
  "/gallery/51.jpg",
  "/gallery/52.jpg",
  "/gallery/53.jpg",
  "/gallery/54.jpg",
  "/gallery/55.jpg",
  "/gallery/56.jpg",
  "/gallery/57.jpg",
  "/gallery/58.jpg",
  "/gallery/60.jpg",
  "/gallery/61.jpg",
  "/gallery/62.jpg",
  "/gallery/63.jpg",

];
